<a href="https://colab.research.google.com/github/posibabu13/Numpy_basics/blob/main/06_Manipulating_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipulating Arrays

Here are two techniques that can be used to change or manipulayte the structure of arrays:
*  Stacking
*  Reshaping

### Stacking

In [5]:
#importing the NumPy library
import numpy as np

# Creating two 1-D arrays with 5 elements using arange
arr_1 = np.arange(1,6)
arr_2 = np.arange(6,11)
print(arr_1)

print(arr_2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [7]:
# Horizonal stacking - Appending the elements in the same row
np.hstack((arr_1,arr_2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# Vertical stacking - Increasing the number of row


# Storing the stacked array for further operations
arr_3 = np.vstack((arr_1,arr_2))
print(arr_3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
# Checking the dimensions of the array
arr_3.ndim

2

In [13]:
# Printing the created array
arr_3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
# Number of rows and columns in the array
np.shape(arr_3)

(2, 5)

### Reshaping

In [17]:
# Creating an array of first ten natural numbers
arr_4 = np.arange(1,11)

# Printing the created array
arr_4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
# Reshaping the 1D array into a 2D array with 2 elements in five rows
arr_5 = arr_4.reshape(5,2)

In [37]:
# Checking the rows and columns in the created array
np.shape(arr_5)

(5, 2)

In [41]:
# Creating a 2D array with 4 elements in five rows (elements from 20 to 39)
arr_6 = np.arange(20,40).reshape(10,2)
print(arr_6)
# Checking the rows and columns in the created array
# arr_5


[[20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]]


In [43]:
# Stacking arr_5 and arr_6

# print(arr_5)
np.vstack((arr_5,arr_6))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [ ]:
# Check the structure of arr_6


In [ ]:
# Reshape the arr_6 to vertically stack with arr_5 
arr_6 = 
arr_6

In [ ]:
# Stacking arr_5 and arr_6


In [45]:
arr_5.shape

(5, 2)

In [50]:
l=arr_6.reshape(5,4)

In [51]:
np.hstack((arr_5,l))

array([[ 1,  2, 20, 21, 22, 23],
       [ 3,  4, 24, 25, 26, 27],
       [ 5,  6, 28, 29, 30, 31],
       [ 7,  8, 32, 33, 34, 35],
       [ 9, 10, 36, 37, 38, 39]])

In [56]:
p=np.array([[1, 5],
 [3, 7],
 [4, 9]])

In [58]:
p.shape

(3, 2)

In [62]:
np.reshape(p, -1).ndim

1

In [68]:
array_1=np.array([[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20]])

In [71]:
array_1.ndim

2

In [73]:
array_1.reshape(5,2)

ValueError: ignored

In [74]:
print(array_1[array_1%2 != 0])

[ 1  3  5  7  9 11 13 15 17 19]


In [75]:

print(array_1[array_1%2 != 0].reshape(5, 2))

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


In [76]:
print(array_1.reshape(5, 4)[array_1%2 != 0])

ValueError: ignored

In [77]:

print(array_1[array_1%2 == 0].reshape(5, 2))

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


In [78]:
p=np.array([[1, 5],
 [3, 7],
 [4, 9]])

In [81]:
np.reshape(p, (1, -1))

array([[1, 5, 3, 7, 4, 9]])

In [82]:
a1=np.array([[7, 13, 14],

[18, 10, 17],

[11, 12, 19]]

)

In [84]:
a1.shape

(3, 3)

In [85]:
a2=np.array([16, 6, 1])

In [86]:
a2.shape

(3,)

In [87]:
np.vstack((a1,a2))

array([[ 7, 13, 14],
       [18, 10, 17],
       [11, 12, 19],
       [16,  6,  1]])

In [98]:
k=np.array([[5, 8, 4, 3]])
k.shape

(1, 4)

In [99]:
h=np.transpose(k,(4,1))

AxisError: ignored

In [97]:
print(h)

<built-in method transpose of numpy.ndarray object at 0x7fec0d753c60>
