In [1]:
import numpy as np
a=np.array([0,1,2,3,4])
print(a)

[0 1 2 3 4]


In [2]:
a=np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
L=range(500)

print([L])

[range(0, 500)]


In [13]:
%timeit [i**2 for in L]
"""The above code is for lists which takes lot of time and is slower than expected"""

SyntaxError: invalid syntax (<unknown>, line 1)

In [12]:
a=np.arange(100)

%timeit a**2

1.03 µs ± 13 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


##### In conclustion we can say numpy is much faster than  lists

In [17]:
#1-D
a=np.array([1,3,4,5,8])

a

In [19]:
# print dimensions
a.ndim

1

In [20]:
a.shape
# prints the shape

(5,)

In [21]:
# we can calculate length of the  array

len(a)

5

In [22]:
# 2-D

b= np.array([[1,2,4],[3,4,5]])

In [23]:
b

array([[1, 2, 4],
       [3, 4, 5]])

In [25]:
b.ndim

2

In [26]:
b.shape

(2, 3)

In [27]:
len(b)

2

In [33]:
# 3-D

c=np.array([
    [[1,2,3],[1,5,6]]
            ,[[4,6,7],[8,9,9]]
])

In [34]:
c

array([[[1, 2, 3],
        [1, 5, 6]],

       [[4, 6, 7],
        [8, 9, 9]]])

In [35]:
c.shape

(2, 2, 3)

In [36]:
c.ndim

3

In [37]:
len(c)

2

In [39]:
"""Short note:
1.1 D array is called vector
2.2 D array is called matrix
3.n D array is called Tensor
"""

'Short note:\n1.1 D array is called vector\n2.2 D array is called matrix\n3.n D array is called Tensor\n'

#### Functions for creating array

In [42]:
 a=np.arange(10)

In [43]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
b=np.arange(1,10,3) # start value , end value, step size

In [45]:
b

array([1, 4, 7])

In [59]:
a=np.linspace(0,4,2)

In [60]:
a

array([0., 4.])

To create ones

In [64]:
g=np.ones((2,2))

In [65]:
g

array([[1., 1.],
       [1., 1.]])

In [70]:
k=np.ones((5,5),int)

In [71]:
k

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [68]:
b=np.zeros((8,8))

In [69]:
b

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

To get identity matrix

In [74]:
c=np.eye(4,3)

In [75]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [76]:
# all diagonal elements are zeros

In [77]:
# create an array using diagonal elements

a=np.diag([1,3,4,6])

In [78]:
a

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [79]:
# To extract only diagonal

np.diag(a)

array([1, 3, 4, 6])

In [80]:
# To generate random numbers

a=np.random.rand(4)

In [81]:
a

array([8.04987600e-01, 6.28278536e-01, 7.32660062e-04, 6.06373203e-01])

The Above is uniform distribution , In general we use uniform distribution 

In [82]:
# Let us now get into normal  distribution
b=np.random.randn(9)

In [83]:
b

array([-0.64968369, -0.27918161, -0.50019913,  1.20730685, -0.47453385,
       -0.59041573,  0.57935136, -0.36695718, -0.08861839])

### Big data types

In [84]:
a=np.arange(10)

In [85]:
a.dtype

dtype('int32')

Data type can be changed too

In [87]:
a=np.arange(10,dtype='float32')

In [88]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [89]:
k=np.zeros((3,3,))

In [90]:
k

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [91]:
k.dtype


dtype('float64')

In [92]:
o=np.ones((4,4))

In [93]:
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [94]:
o.dtype

dtype('float64')

In [95]:
# Complex data types
d=np.array([1+9j, 2+4j])

In [96]:
d

array([1.+9.j, 2.+4.j])

In [98]:
d.dtype

dtype('complex128')

In [99]:
b=np.array([True,False,True])

In [100]:
b

array([ True, False,  True])

In [101]:
b.dtype

dtype('bool')

In [102]:
s=np.array(['Ram','Rohan','posibabu'])

In [103]:
s

array(['Ram', 'Rohan', 'posibabu'], dtype='<U8')

In [104]:
s.dtype

dtype('<U8')

### indexing and slicing

In [106]:
p=np.arange(10)

In [107]:
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
p[5]

5

In [109]:
p=np.diag([1,2,3])

In [110]:
p

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [111]:
p[2,2]

3

In [112]:
p[2,1]=5

In [113]:
p

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

###slicing

In [114]:
a=np.arange(10)

In [115]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
a[1:8:2]

array([1, 3, 5, 7])

In [117]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
a[5:]=55

In [119]:
a

array([ 0,  1,  2,  3,  4, 55, 55, 55, 55, 55])

In [120]:
b=np.arange(5)

In [121]:
b

array([0, 1, 2, 3, 4])

In [125]:
a[5:]=b[ : :-1]

In [126]:
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [127]:
a=np.arange(10)

In [129]:
b=a[::2]

In [130]:
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [131]:
np.shares_memory(a,b)

True

In [132]:
b[0]=10

In [134]:

a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [135]:
k=np.arange(4)

In [136]:
l=k[::3]

In [137]:
l

array([0, 3])

In [138]:
k

array([0, 1, 2, 3])

In [139]:
l[0]=10

In [140]:
k

array([10,  1,  2,  3])

In [141]:
l

array([10,  3])

In [142]:
c=np.arange(9)

In [143]:
d=c[::2].copy()

In [144]:
d

array([0, 2, 4, 6, 8])

In [145]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [146]:
np.shares_memory(c,d)

False

In [153]:
d[0]=5

In [154]:
d

array([5, 2, 4, 6, 8])

In [155]:
c

array([5, 1, 2, 3, 5, 5, 6, 7, 8])

In [158]:
a=np.random.randint(0,20,15)

In [159]:
a

array([ 4, 15, 15, 10,  5,  8,  6, 15, 14,  9, 10, 12, 12, 17, 15])

In [160]:
mask =(a%2==0)

In [161]:
extract_a=a[mask]

In [162]:
extract_a

array([ 4, 10,  8,  6, 14, 10, 12, 12])

In [163]:
a[mask]=-1

In [164]:
extract_a

array([ 4, 10,  8,  6, 14, 10, 12, 12])

In [165]:
a

array([-1, 15, 15, -1,  5, -1, -1, 15, -1,  9, -1, -1, -1, 17, 15])

In [168]:
a=np.arange(0,100,10)

In [169]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [170]:
# we can pull out index elements
a[[2,3,4,2,2,2]]

array([20, 30, 40, 20, 20, 20])

In [171]:
# assign new values to indices

a[[7,8]]=-200

In [172]:
a

array([   0,   10,   20,   30,   40,   50,   60, -200, -200,   90])

### Numerical operations on Numpy

In [173]:
a=np.arange(5)

In [174]:
a

array([0, 1, 2, 3, 4])

In [176]:
a=a+2

In [177]:
a

array([2, 3, 4, 5, 6])

In [178]:
a**2

array([ 4,  9, 16, 25, 36], dtype=int32)

In [180]:
a=np.ones((2,2))

In [181]:
a

array([[1., 1.],
       [1., 1.]])

In [185]:
c=a+1

In [183]:
b=np.array([[1,3],[2,5]])

In [184]:
a*b

array([[1., 3.],
       [2., 5.]])

In [186]:
k=c*b

array([[ 2.,  6.],
       [ 4., 10.]])

In [188]:
k=np.diag([1,2])

In [189]:
k

array([[1, 0],
       [0, 2]])

In [190]:
c=np.diag([1,2,4,4])
print(c)
print("******************")
print(c*c)
print("=========")
print(c.dot(c))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 4 0]
 [0 0 0 4]]
******************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0 16  0]
 [ 0  0  0 16]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0 16  0]
 [ 0  0  0 16]]


In [191]:
# comparisions

a=np.array([1,2,4])
b=np.array([3,5,3])

a==b

array([False, False, False])

In [192]:
a>b

array([False, False,  True])

In [193]:
a>=b

array([False, False,  True])

In [194]:
a<=b

array([ True,  True, False])

In [196]:
np.array_equal(a,b)

False

#### Logic operations

In [197]:
a=np.array([1,0,1,0],dtype=bool)
b=np.array([1,0,0,0],dtype=bool)

In [198]:
np.logical_or(a,b)

array([ True, False,  True, False])

In [199]:
np.logical_and(a,b)

array([ True, False, False, False])

In [200]:
np.logical_not(a,b)

array([False,  True, False,  True])

In [204]:
np.logical_or(a,b)

array([ True,  True,  True,  True])

##### Transendental operations

In [205]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [210]:
np.log(a)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [208]:
import warnings

In [209]:
warnings.filterwarnings("ignore")

In [211]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

#### shape mismatch

In [212]:
a=np.array([1,2,4,4])
a+np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

Above is mismatch error

In [213]:
a

array([1, 2, 4, 4])

In [214]:
a.sum()

11

In [215]:
a=np.array([[1,2,3],[2,5,6]])

In [216]:
a

array([[1, 2, 3],
       [2, 5, 6]])

In [218]:
a.sum(axis=0)

array([3, 7, 9])

In [220]:
a.sum(axis=1)

array([ 6, 13])

In [221]:
a

array([[1, 2, 3],
       [2, 5, 6]])

In [222]:
a.min()

1

In [223]:
a=np.array([3,5,6,2])

In [224]:
a.min()

2

In [225]:
a.max()

6

In [226]:
a.sum()

16

In [227]:
# to find index of min element 
a.argmin()

3

In [228]:
# to find index of max element
a.argmax()

2

In [229]:
np.all([True,True,False])

False

In [230]:
np.all([True,True,True])

True

In [231]:
np.any([True,False,False])

True

In [232]:
np.any([False,False,False])

False

In [233]:
a=np.zeros((50,50))

In [234]:
np.any(a!=0)

False

In [235]:
np.all(a==a)

True

In [236]:
a=np.array([1,2,4,2])
b=np.array([2,3,2,2])
c=np.array([1,2,3,4])

((a<=b) & (a<=c)).all()

False

In [238]:
x=np.array([1,2,4,3])
y=np.array([[1,3,4],[2,5,5]])


In [239]:
x.mean()

2.5

In [240]:
y.mean()

3.3333333333333335

In [242]:
np.median(x)

2.5

In [243]:
20/6

3.3333333333333335

In [244]:
np.median(y)

3.5

In [246]:
y

array([[1, 3, 4],
       [2, 5, 5]])

In [245]:
np.median(y,axis=0)

array([1.5, 4. , 4.5])

In [251]:
np.median(y,axis=1)

array([3., 5.])

In [252]:
np.median(y,axis=-1)

array([3., 5.])

In [253]:
x.std()

1.118033988749895

In [254]:
data=np.loadtxt('populations.txt')

In [255]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [256]:
years,hares,lynxes,carrots=data.T

In [258]:
print(years)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [259]:
print(hares)

[30000. 47200. 70200. 77400. 36300. 20600. 18100. 21400. 22000. 25400.
 27100. 40300. 57000. 76600. 52300. 19500. 11200.  7600. 14600. 16200.
 24700.]


In [263]:
population=data[:,1:]

In [264]:
population

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [265]:
population.mean(axis=0)

array([34080.95238095, 20166.66666667, 42400.        ])

In [266]:
population.std(axis=1)

array([18176.23601177, 19614.67704439, 24668.33327703, 19225.21492439,
       10030.73055941,  9530.41913501,  9458.79954798, 12319.18106946,
       14923.434219  , 13472.52347888, 15759.51211879, 16967.22330456,
       18751.53327064, 23553.39088586,  5266.87763291, 13018.02169644,
       10757.4263754 , 14578.82787546, 14819.88154099, 13501.68713737,
       15873.31793363])

In [267]:
np.median(population)

36700.0

In [268]:
np.argmax(population,axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [269]:
np.argmin(population,axis=0)

array([17,  0, 16], dtype=int64)

In [272]:
a=np.tile(np.arange(0,40,10),(3,1))

In [273]:
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [275]:
a=a.T

In [276]:
b=np.array([1,2,4])

In [277]:
a+b

array([[ 1,  2,  4],
       [11, 12, 14],
       [21, 22, 24],
       [31, 32, 34]])

In [278]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [279]:
# making 1 D to 2D array
a=np.array([1,3,5,3])


In [280]:
a.shape


(4,)

In [281]:
a=a[: ,np.newaxis]

In [282]:
a

array([[1],
       [3],
       [5],
       [3]])

In [283]:
a.shape

(4, 1)

In [284]:
b

array([1, 2, 4])

In [285]:
a+b

array([[2, 3, 5],
       [4, 5, 7],
       [6, 7, 9],
       [4, 5, 7]])

In [286]:
a=np.array([[1,2,4],[2,5,5]])

In [287]:
a

array([[1, 2, 4],
       [2, 5, 5]])

In [288]:
a.ravel()

array([1, 2, 4, 2, 5, 5])

In [289]:
a.T

array([[1, 2],
       [2, 5],
       [4, 5]])

In [290]:
a.T.ravel()

array([1, 2, 2, 5, 4, 5])

In [291]:
a.shape


(2, 3)

In [292]:
a

array([[1, 2, 4],
       [2, 5, 5]])

In [293]:
b=a.ravel()

In [294]:
b

array([1, 2, 4, 2, 5, 5])

In [295]:
b.reshape((2,3))

array([[1, 2, 4],
       [2, 5, 5]])